adminUser: admin
adminPassword: admin

ingress:
  enabled: true
  hosts:
    - grafana.minikube

persistence:
  enabled: false

sidecar:
  dashboards:
    enabled: true

  datasources:
    enabled: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubeless:
      url: https://github.com/evry-bergen/kubeless-workshop/raw/master/config/dashboard.json
