apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubeless.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "kubeless.name" . }}
    helm.sh/chart: {{ include "kubeless.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    kubeless: config
data:
  builder-image: "{{ .Values.config.builderImage }}"
  builder-image-secret: "{{ .Values.config.builderImagePullSecret }}"
  deployment: "{{ .Values.config.deploymentTemplate }}"
  enable-build-step: "{{ .Values.config.enableBuildStep }}"
  function-registry-tls-verify: "{{ .Values.config.functionRegistryTLSVerify }}"
  ingress-enabled: "{{ .Values.config.ingressEnabled }}"
  provision-image: "{{ .Values.config.provisionImage }}"
  provision-image-secret: "{{ .Values.config.provisionImagePullSecret }}"
  runtime-images: |-
{{ .Values.config.runtimeImages | indent 4 }}
  service-type: "{{ .Values.config.serviceType }}"
