{{- if .Values.natsTrigger.enabled -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natstriggers.kubeless.io
description: CRD object for NATS trigger type
spec:
  group: kubeless.io
  names:
    kind: NATSTrigger
    plural: natstriggers
    singular: natstrigger
  scope: Namespaced
  version: v1beta1
{{- end }}
