{{- if .Values.natsTrigger.enabled -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "kubeless.fullname" . }}-nats-trigger-controller
  labels:
    app.kubernetes.io/name: {{ include "kubeless.name" . }}
    helm.sh/chart: {{ include "kubeless.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    kubeless: controller
    kubeless: nats-trigger-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubeless.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      kubeless: nats-trigger-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubeless.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        kubeless: nats-trigger-controller
    spec:
      containers:
        - name: nats-trigger-controller
          image: "{{ .Values.natsTrigger.deployment.image.repository }}:{{ .Values.natsTrigger.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.natsTrigger.deployment.image.pullPolicy }}
          resources:
{{ toYaml .Values.natsTrigger.deployment.resources | indent 12 }}
          env:
{{ include "kubeless.controller.env" . | indent 12 }}
            - name: NATS_URL
              value: "nats://{{ .Values.natsTrigger.deployment.env.natsUrl }}"
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}

    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}

    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

{{- if .Values.rbac.enabled }}
      serviceAccountName: {{ include "kubeless.fullname" . }}-controller
{{- end }}
{{- end }}
