{{- if and .Values.rbac.enabled .Values.ui.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeless.fullname" . }}-ui
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "kubeless.fullname" . }}-ui
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - kubeless.io
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - proxy
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - get
  # the 'create' verb is required because otherwise POST requests are blocked
  - create
  - proxy
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeless.fullname" . }}-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeless.fullname" . }}-ui
subjects:
- kind: ServiceAccount
  name: {{ include "kubeless.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
{{- end }}
