apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-java-spring
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/erasmolpa/helloworld-java-spring
          env:
            - name: TARGET
              value: "Java Spring Sample v1"
