apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: github-client
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: erasmolpa/github-client:0.0.9
          env:
            - name: TARGET
              value: "Github client"
